// RADIO
#define RAD_FREQ 433000000
#define RESET 22
#define NSS 15
#define DI00 13

// STEERING POT
#define JOYSTICK 2

// THROTTLE POT
#define TRIGGER 4

// LIGHT SWITCH
#define LIGHTS 17

// DISPLAY
#define SCREEN_WIDTH 128
#define SCREEN_HEIGHT 32
#define OLED_RESET -1 
#define SCREEN_ADDRESS 0x3C 